### ISSUE TITLE
Plugin failing in idea-2017.x

### ISSUE THREAD

**Issue by jjishin** [kontext-e/AutoFillingCallArguments#1] opened 2017-04-28 06:37 UTC
Hi,

Its a very nice plugin, and was working flawless in 2016.x version. But started failing in idea-2017.x version with following error.
`
null
java.lang.NullPointerException
	at de.kontext_e.idea.plugins.autofill.AutoFillCallArguments.invoke(AutoFillCallArguments.java:27)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.invoke(PsiElementBaseIntentionAction.java:42)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:65)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:196)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:198)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:186)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.b(ShowIntentionActionsHandler.java:185)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:184)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.c(IntentionListStep.java:273)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

And intellij version

IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by kontext-e** [comment] 2017-04-28 17:44
Just tried IDEA 2017.1, Build #IC-171.3780.107, built on March 22, 2017
Works fine so far.
BUT: a problem I'm currently working on is that if the method is overloaded, the plugin gets confused and may throw a NPE. Could you check if that could be the case, please?

**Comment by iddinkwessel** [comment] 2019-06-20 16:11
> BUT: a problem I'm currently working on is that if the method is overloaded, the plugin gets confused and may throw a NPE. Could you check if that could be the case, please?

Too bad you didn't get the answer on this. Yes the NPE is on overloaded methods.

**Comment by delgurth** [comment] 2019-06-20 16:13
Too bad you didn't get a reply on your question.

> BUT: a problem I'm currently working on is that if the method is overloaded, the plugin gets confused and may throw a NPE. Could you check if that could be the case, please?

Yes, this happens on overloaded methods. Then you get a NPE. 

I'm wondering if we can get this to work together with the "Show parameter names hints on completion" feature, since IDEA is able to show the parameter names now, perhaps the plugin can use those names?

**Comment by kontext-e** [comment] 2019-07-04 08:43
I'd be happy to get this working. Until now I couldn't find the time to dig deeper into the IntelliJ source to find the right method calls to make, so in a first step, I only added a null check.
But PRs are welcome ;)

**Comment by kontext-e** [comment] 2019-07-04 21:58
Now I found a basic workaround: in case of overloaded methods, the one with the most parameters is chosen. If that was the wrong one, it is quite easy to remove the unwanted parameters.
Still working on a better solution based on code completion actions, but that may take a while (depending on how much time I'm able to spend with this plugin).
I'm considering to publish this intermediate version as a 1.0.1 or so.

**Comment by mousecray** [comment] 2020-03-19 18:28
Oh, I have the same problem... I work on the
`IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020
Runtime version: 1.8.0_211-b12 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0`
And I get that error:
`java.lang.NullPointerException
	at de.kontext_e.idea.plugins.autofill.AutoFillCallArguments.invoke(AutoFillCallArguments.java:27)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.invoke(PsiElementBaseIntentionAction.java:41)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:58)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:181)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$5(ShowIntentionActionsHandler.java:236)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:101)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:238)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$null$3(ShowIntentionActionsHandler.java:213)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$4(ShowIntentionActionsHandler.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:211)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1434)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2418)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:177)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:159)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1430)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:151)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:104)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:183)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:133)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:123)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:119)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:252)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:461)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:415)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:356)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:269)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:367)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:347)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:93)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
Please fix this, I really miss this plugin. Thanks)

**Comment by mousecray** [comment] 2020-03-20 18:28
I tried to clone the repository in order to fix this error myself, however, it looks like it has already been fixed...

**Comment by kontext-e** [comment] 2020-03-20 20:02
Well, the NPE itself is fixed, but unfortunately the root cause not: a popup should be shown to select the overloaded method that is meant. Until now I look for some resources and poked in IntelliJ source code, but did not found the right way to do that.

**Comment by mousecray** [comment] 2020-03-20 20:14
I do not understand the source code of inteleji idea at all, but I wish you good luck) I belive you can fix it! It might be worth a try writing to technical support of Idea?

**Comment by CymricNPG** [comment] 2023-04-09 10:43
I modified your code a bit to fix the NPE and added the popup. A prototype release can be found at https://github.com/CymricNPG/AutoFillingCallArguments/releases/tag/1.2, maybe you can include the changes in your plugin.

**Comment by omasseau** [comment] 2023-04-18 15:45
> I modified your code a bit to fix the NPE and added the popup. A prototype release can be found at https://github.com/CymricNPG/AutoFillingCallArguments/releases/tag/1.2, maybe you can include the changes in your plugin.

Thanks your version fixes the bug :)

For those who want to install it manually, download the AutofillParameter-1.2.zip, then : 
- Open IntelliJ IDEA and go to File > Settings (on Windows) or IntelliJ IDEA > Preferences (on Mac).
- In the Settings/Preferences dialog, select Plugins.
 - Click the gear icon on the top right corner of the dialog and select "Install Plugin from Disk".
- In the file dialog that appears, navigate to the downloaded plugin file and select it.
- Click OK to install the plugin.
- Restart IntelliJ IDEA to activate the newly installed plugin.

**Comment by JensNercheKE** [comment] 2023-04-21 12:55
@CymricNPG thank you very much. I backported your code to be able to support older versions as well, updated plugin is uploaded and currently under review by JetBrains. Will close this issue once the plugin passed the review.

**Comment by JensNercheKE** [comment] 2023-05-16 06:29
Thanks to @CymricNPG a new version 1.2 could be released which asks for the overloaded method to use.

**Closed as completed by JensNercheKE** 2023-05-16 06:29 UTC
Labels: bug
